package com.varitas.gokulpos.tablet.response

import com.google.gson.annotations.SerializedName
import com.varitas.gokulpos.tablet.request.ChangePriceRequest

data class ProductDetail(
    @SerializedName("productName"          ) var productName          : String?                      = null,
    @SerializedName("sku"                  ) var sku                  : String?                      = null,
    @SerializedName("manufacrturerPartNo"  ) var manufacrturerPartNo  : String?                      = null,
    @SerializedName("productTypeId"        ) var productTypeId        : Int?                         = null,
    @SerializedName("productType"          ) var productType          : String?                      = null,
    @SerializedName("shortDescription"     ) var shortDescription     : String?                      = null,
    @SerializedName("fullDescription"      ) var fullDescription      : String?                      = null,
    @SerializedName("vendorId"             ) var vendorId             : Int?                         = null,
    @SerializedName("vendorName"           ) var vendorName           : String?                      = null,
    @SerializedName("sizeId"               ) var sizeId               : Int?                         = null,
    @SerializedName("sizeValue"            ) var sizeValue            : String?                      = null,
    @SerializedName("packId"               ) var packId               : Int?                         = null,
    @SerializedName("packValue"            ) var packValue            : String?                      = null,
    @SerializedName("showOnHomePage"       ) var showOnHomePage       : Boolean?                      = null,
    @SerializedName("warehouseId"          ) var warehouseId          : Int?                      = null,
    @SerializedName("modelNo"              ) var modelNo              : String?                      = null,
    @SerializedName("unitType"             ) var unitType             : Int?                         = null,
    @SerializedName("serialNo"             ) var serialNo             : String?                      = null,
    @SerializedName("productCode"          ) var productCode          : Int?                         = null,
    @SerializedName("isPublish"            ) var isPublish            : Boolean?                      = null,
    @SerializedName("hsncode"              ) var hsnCode              : String?                      = null,
    @SerializedName("uom"                  ) var uom                  : String?                      = null,
    @SerializedName("subCategoryId"        ) var subCategoryId        : Int?                         = null,
    @SerializedName("subCategoryName"      ) var subCategoryName      : String?                      = null,
    @SerializedName("parentCategoryId"     ) var parentCategoryId     : Int?                         = null,
    @SerializedName("parentCategoryName"   ) var parentCategoryName   : String?                      = null,
    @SerializedName("manufactureId"        ) var manufactureId        : Int?                         = null,
    @SerializedName("manufactureName"      ) var manufactureName      : String?                      = null,
    @SerializedName("isManufactureBarcode" ) var isManufactureBarcode : Boolean?                     = null,
    @SerializedName("departmentId"         ) var departmentId         : Int?                         = null,
    @SerializedName("departmentName"       ) var departmentName       : String?                      = null,
    @SerializedName("isCountyTax"          ) var isCountyTax          : Boolean?                      = null,
    @SerializedName("promptForPrice"       ) var promptForPrice       : Boolean?                     = null,
    @SerializedName("promptForQuantity"    ) var promptForQuantity    : Boolean?                     = null,
    @SerializedName("nonPluitem"           ) var nonPluItem           : Boolean?                     = null,
    @SerializedName("taxViewModels"        ) var taxViewModels        : ArrayList<Tax>     = arrayListOf(),
    @SerializedName("priceMapModel"        ) var priceMapModel        : ChangePriceRequest?               = ChangePriceRequest(),
    @SerializedName("solAmtModel"          ) var solAmtModel          : ArrayList<String>            = arrayListOf(),
    @SerializedName("manufacturerPartNo"   ) var manufacturerPartNo   : String?                      = null,
    @SerializedName("listBarcodeModels"    ) var listBarcodeModels    : ArrayList<UPC> = arrayListOf(),
    @SerializedName("id"                   ) var id                   : Int?                         = null,
    @SerializedName("status"               ) var status               : Int?                         = null,
    @SerializedName("statusTitle"          ) var statusTitle          : String?                      = null,
    @SerializedName("statusCls"            ) var statusCls            : String?                      = null,
    @SerializedName("actionBy"            ) var actionBy            : Int?                         = null,
    @SerializedName("createdOnUtc"         ) var createdOnUtc         : String?                      = null,
    @SerializedName("modifiedOnUtc"        ) var modifiedOnUtc        : String?                      = null,
    @SerializedName("storeId"              ) var storeId              : String?                      = null
)