package com.varitas.gokulpos.utilities

object Enums {
    enum class ClickEvents {
        CANCEL, SAVE, VIEW, EDIT, PRICE, ERROR, QUANTITY, UPDATE
    }

    enum class Attributes {
        SIZE, PACK
    }

    enum class Menus {
        ANALYSIS, MANAGEMENT, STOCK, PRINT_LABEL, HOLD_ORDERS, SETTINGS, NOTIFICATIONS, ORDERS, REGISTRATION, DEVICES, DEPARTMENT, CATEGORY, BRAND, TAX, SPECIFICATION, FACILITY, UOM, VENDOR, GROUP, CUSTOMERS, EMPLOYEES, REPORTS, DAILY_REPORTS, SALES_SUMMARY, CASH_AND_SALES, Z_REPORT, DAY_SALES, DEPARTMENT_SALES, TRANSACTION_LOG, OPERATION_RECORD, PRODUCTS, DASHBOARD, TENDER, PURCHASE, INVOICE
    }
}